#!/usr/bin/env bash

APP=$1
PROJECT=$2

if [ -z "$PROJECT" ]; then
    echo "bash -s <folder>"
    exit
fi

git clone git@github.com:${APP}.git $PROJECT

cd $PROJECT

rm -rf .git

git init

cp .env.example .env
